# TensorFlow の操作

## 必要なライブラリのインポート

In [1]:
import tensorflow as tf

# 1. Tensor オブジェクト

## 定数の Tensor の生成

In [2]:
a = tf.constant(5, dtype='float32') # スカラーを生成
A = tf.constant([[1, 2], [3, 4]], dtype='float32') # 2次元配列を生成
print('a:', a,)
print('A:', A, '\n')

a: tf.Tensor(5.0, shape=(), dtype=float32)
A: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32) 



## Tensor の演算

In [3]:
b = tf.constant(2, dtype='float32') # スカラーを生成
B = tf.constant([[10, 20], [30, 40]], dtype='float32') # 2次元配列を生成
print('tf.add(a, b):', tf.add(a, b)) # tf.add 関数で加算
print('a + b:', a + b) # 加算
print('a - b:', a - b) # 減算
print('a * b:', a * b) # 乗算
print('a / b:', a / b) # 除算
print('a % b:', a % b) # 剰余
print('a // b:', a // b) # 切り捨て除算
print('A + B:', A + B) # 2次元配列同士の加算

tf.add(a, b): tf.Tensor(7.0, shape=(), dtype=float32)
a + b: tf.Tensor(7.0, shape=(), dtype=float32)
a - b: tf.Tensor(3.0, shape=(), dtype=float32)
a * b: tf.Tensor(10.0, shape=(), dtype=float32)
a / b: tf.Tensor(2.5, shape=(), dtype=float32)
a % b: tf.Tensor(1.0, shape=(), dtype=float32)
a // b: tf.Tensor(2.0, shape=(), dtype=float32)
A + B: tf.Tensor(
[[11. 22.]
 [33. 44.]], shape=(2, 2), dtype=float32)


## 変数の Tensor の生成と演算

In [4]:
d = tf.Variable([10, 20], dtype='float32') # 1次元配列の変数を生成
e = tf.Variable([1, 2], dtype='float32') # 1次元配列の変数を生成
print(d + e) # d と e の和

tf.Tensor([11. 22.], shape=(2,), dtype=float32)


## NumPy のオブジェクトに変換

In [5]:
A_np = A.numpy() # 定数の A を NumPy のオブジェクトに変換
print('type(A_np):', type(A_np))
print('A_np:', A_np)

print() # 改行

d_np = d.numpy() # 変数の d を NumPy のオブジェクトに変換
print('type(d_np):', type(d_np))
print('d_np":', d_np)

type(A_np): <class 'numpy.ndarray'>
A_np: [[1. 2.]
 [3. 4.]]

type(d_np): <class 'numpy.ndarray'>
d_np": [10. 20.]


## ndarray から Tensor へのキャスト

In [6]:
print(tf.cast(A_np, tf.float32)) # A_np を Tensor へキャスト

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


# 3. TensorFlow による勾配降下法の体験

## tf.GradientTape による勾配の計算

In [7]:
x = tf.Variable(3.0)

# 監視対象の変数と微分対象の関数をセット
with tf.GradientTape() as tape:
    tape.watch(x)
    y = x ** 2

# 勾配を計算
dy_dx = tape.gradient(y, x)

# 勾配を表示
print(dy_dx.numpy())

6.0


## 勾配降下法の体験

### 勾配降下法の関数を定義

In [8]:
def gradient_descent(learning_rate):
    x = tf.Variable(3.0)
    
    # スタート時点での x と y を表示
    print('  (x, y) = ({0:.2f}, {1:.2f})'.format(x.numpy(), (x ** 2).numpy()))
    
    # 勾配降下法を5ステップ実行
    for i in range(5):
        with tf.GradientTape() as tape:
            tape.watch(x)
            y = x ** 2
        dy_dx = tape.gradient(y, x)
        x.assign(x - learning_rate * dy_dx) # x を更新 (x = x - learning_rate * dy_dx)
        
        # x と y を表示
        print('  (x, y) = ({0:.2f}, {1:.2f})'.format(x.numpy(), (x ** 2).numpy()))

### 複数の学習率で勾配降下法を実行

In [9]:
for learning_rate in (0.3, 0.8, 1.2):
    print('Learning rate =', learning_rate)
    gradient_descent(learning_rate)
    print()

Learning rate = 0.3
  (x, y) = (3.00, 9.00)
  (x, y) = (1.20, 1.44)
  (x, y) = (0.48, 0.23)
  (x, y) = (0.19, 0.04)
  (x, y) = (0.08, 0.01)
  (x, y) = (0.03, 0.00)

Learning rate = 0.8
  (x, y) = (3.00, 9.00)
  (x, y) = (-1.80, 3.24)
  (x, y) = (1.08, 1.17)
  (x, y) = (-0.65, 0.42)
  (x, y) = (0.39, 0.15)
  (x, y) = (-0.23, 0.05)

Learning rate = 1.2
  (x, y) = (3.00, 9.00)
  (x, y) = (-4.20, 17.64)
  (x, y) = (5.88, 34.57)
  (x, y) = (-8.23, 67.77)
  (x, y) = (11.52, 132.82)
  (x, y) = (-16.13, 260.33)



# 4. Keras の最適化アルゴリズムの利用

## Keras のインポート

In [10]:
import tensorflow.keras as keras

## 勾配降下法の実行

In [12]:
for learning_rate in (0.3, 0.8, 1.2):
    x = tf.Variable(3.0)
    
    # ①. 最適化の対象の関数（目的関数）
    objective = lambda: x ** 2
    
    # 学習率を表示
    print('Learning rate =', learning_rate)
    
    # スタート時点での x と y を表示
    print('  (x, y) = ({0:.2f}, {1:.2f})'.format(x.numpy(), objective().numpy()))

    # ②. SGD のインスタンスを生成
    opt = keras.optimizers.SGD(learning_rate)
    
    # 勾配降下を5ステップ実行
    for i in range(5):
        
        # ③. 最小化
        opt.minimize(objective, var_list = [x])
        
        # x と y を表示
        print('  (x, y) = ({0:.2f}, {1:.2f})'.format(x.numpy(), objective().numpy()))
    
    print()

Learning rate = 0.3
  (x, y) = (3.00, 9.00)
  (x, y) = (1.20, 1.44)
  (x, y) = (0.48, 0.23)
  (x, y) = (0.19, 0.04)
  (x, y) = (0.08, 0.01)
  (x, y) = (0.03, 0.00)

Learning rate = 0.8
  (x, y) = (3.00, 9.00)
  (x, y) = (-1.80, 3.24)
  (x, y) = (1.08, 1.17)
  (x, y) = (-0.65, 0.42)
  (x, y) = (0.39, 0.15)
  (x, y) = (-0.23, 0.05)

Learning rate = 1.2
  (x, y) = (3.00, 9.00)
  (x, y) = (-4.20, 17.64)
  (x, y) = (5.88, 34.57)
  (x, y) = (-8.23, 67.77)
  (x, y) = (11.52, 132.82)
  (x, y) = (-16.13, 260.33)



## Adam

### Adam の実行

In [13]:
for learning_rate in (0.3, 0.8, 1.2):
    x = tf.Variable(3.0)
    
    # 最適化の対象の関数（目的関数）
    objective = lambda: x ** 2
    
    # 学習率を表示
    print('Learning rate =', learning_rate)
    
    # スタート時点での x と y を表示
    print('  (x, y) = ({0:.2f}, {1:.2f})'.format(x.numpy(), objective().numpy()))
    
    # SGD を Adam に変更するだけ
    # opt = keras.optimizers.SGD(learning_rate)
    opt = keras.optimizers.Adam(learning_rate)
    
    # Adam を5ステップ実行
    for i in range(5):
        
        # 最小化
        opt.minimize(objective, var_list = [x])
        
        # x と y を表示
        print('  (x, y) = ({0:.2f}, {1:.2f})'.format(x.numpy(), objective().numpy()))
    
    print()

Learning rate = 0.3
  (x, y) = (3.00, 9.00)
  (x, y) = (2.70, 7.29)
  (x, y) = (2.40, 5.77)
  (x, y) = (2.10, 4.43)
  (x, y) = (1.81, 3.28)
  (x, y) = (1.52, 2.32)

Learning rate = 0.8
  (x, y) = (3.00, 9.00)
  (x, y) = (2.20, 4.84)
  (x, y) = (1.42, 2.00)
  (x, y) = (0.67, 0.45)
  (x, y) = (-0.01, 0.00)
  (x, y) = (-0.59, 0.35)

Learning rate = 1.2
  (x, y) = (3.00, 9.00)
  (x, y) = (1.80, 3.24)
  (x, y) = (0.65, 0.42)
  (x, y) = (-0.36, 0.13)
  (x, y) = (-1.12, 1.25)
  (x, y) = (-1.53, 2.34)

