# ディープラーニングに必要な数学と NumPy の操作

# 1. NumPy の基本

## NumPy のインポート

In [2]:
import numpy as np

## ndarray による1次元配列の例

In [3]:
a1 = np.array([1, 2, 3]) # 1次元配列を生成
print('変数の型:',type(a1))
print('データの型 (dtype):', a1.dtype)
print('要素の数 (size):', a1.size)
print('形状 (shape):', a1.shape)
print('次元の数 (ndim):', a1.ndim)
print('中身:', a1)

変数の型: <class 'numpy.ndarray'>
データの型 (dtype): int64
要素の数 (size): 3
形状 (shape): (3,)
次元の数 (ndim): 1
中身: [1 2 3]


## ndarray による1次元配列の例

In [4]:
a2 = np.array([[1, 2, 3],[4, 5, 6]], dtype='float32') # データ型 float32 の2次元配列を生成
print('データの型 (dtype):', a2.dtype)
print('要素の数 (size):', a2.size)
print('形状 (shape):', a2.shape)
print('次元の数 (ndim):', a2.ndim)
print('中身:', a2)

データの型 (dtype): float32
要素の数 (size): 6
形状 (shape): (2, 3)
次元の数 (ndim): 2
中身: [[1. 2. 3.]
 [4. 5. 6.]]


# 2. ベクトル（1次元配列）

## ベクトル a の生成（1次元配列の生成）

In [5]:
a = np.array([4, 1])

## ベクトルのスカラー倍

In [6]:
for k in (2, 0.5, -1):
    print(k * a)

[8 2]
[2.  0.5]
[-4 -1]


## ベクトルの和と差

In [7]:
b = np.array([1, 2]) # ベクトル b の生成
print('a + b =', a + b) # ベクトル a とベクトル b　の和
print('a - b =', a - b) # ベクトル a とベクトル b　の差

a + b = [5 3]
a - b = [ 3 -1]


# 3. 行列（2次元配列）

## 行列を2次元配列で生成

In [8]:
A = np.array([[1, 2], [3 ,4], [5, 6]])
B = np.array([[5, 6], [7 ,8]])
print('A:\n', A)
print('A.shape:', A.shape )
print()
print('B:\n', B)
print('B.shape:', B.shape )

A:
 [[1 2]
 [3 4]
 [5 6]]
A.shape: (3, 2)

B:
 [[5 6]
 [7 8]]
B.shape: (2, 2)


## 行列Aの i = 3, j = 2 にアクセス

In [9]:
print(A[2][1])

6


## A の転置行列

In [10]:
print(A.T)

[[1 3 5]
 [2 4 6]]


## 行列のスカラー倍

In [11]:
print(2 * A)

[[ 2  4]
 [ 6  8]
 [10 12]]


## 行列の和と差

In [12]:
print('A + A:\n', A + A) # 行列 A と行列 A の和
print()
print('A - A:\n', A - A) # 行列 A と行列 A の差

A + A:
 [[ 2  4]
 [ 6  8]
 [10 12]]

A - A:
 [[0 0]
 [0 0]
 [0 0]]


## 行列 A と行列 B の和

In [13]:
print(A + B)

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

## 行列の積

In [14]:
print(np.dot(A, B))

[[19 22]
 [43 50]
 [67 78]]


## 積 BA

In [15]:
print(np.dot(B, A))

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

## アダマール積 A $\circ$ A

In [17]:
print(A * A)

[[ 1  4]
 [ 9 16]
 [25 36]]


## 行列 X と行ベクトル a の積

In [18]:
X  = np.array([[0, 1, 2, 3, 4],
               [5, 6, 7, 8, 9]])
a = np.array([[1, 2, 3, 4, 5]])
print('X.shape:', X.shape)
print('a.shape:', a.shape)
print(np.dot(X, a))

X.shape: (2, 5)
a.shape: (1, 5)


ValueError: shapes (2,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

## 行列 X と列ベクトル a の積

In [34]:
X  = np.array([[0, 1, 2, 3, 4],
               [5, 6, 7, 8, 9]])
a = np.array([[1], 
                        [2],
                        [3],
                        [4],
                        [5]])
print('X.shape:', X.shape)
print('a.shape:', a.shape)
Xa = np.dot(X, a)
print('Xa.shape:', Xa.shape)
print('Xa:\n', Xa)

X.shape: (2, 5)
a.shape: (5, 1)
Xa.shape: (2, 1)
Xa:
 [[ 40]
 [115]]


## NumPy による行列 X と1次元配列の積

In [35]:
X  = np.array([[0, 1, 2, 3, 4],
               [5, 6, 7, 8, 9]])
a = np.array([1, 2, 3, 4, 5]) # 1次元配列で生成
print('X.shape:', X.shape)
print('a.shape:', a.shape)
Xa = np.dot(X, a)
print('Xa.shape:', Xa.shape)
print('Xa:\n', Xa)

X.shape: (2, 5)
a.shape: (5,)
Xa.shape: (2,)
Xa:
 [ 40 115]


In [24]:
import numpy as np
np.array([1, 0.1])

array([1. , 0.1])

# 4. ndarray の 軸（axis）について

## Aの合計を計算

In [25]:
np.sum(A)

21

## axis = 0 で A の合計を計算

In [26]:
print(np.sum(A, axis=0).shape)
print(np.sum(A, axis=0))

(2,)
[ 9 12]


## axis = 1 で A の合計を計算

In [27]:
print(np.sum(A, axis=1).shape)
print(np.sum(A, axis=1))

(3,)
[ 3  7 11]


## np.max 関数の利用例

In [28]:
Y_hat = np.array([[3, 4], [6, 5], [7, 8]]) # 2次元配列を生成
print(np.max(Y_hat)) # axis 指定なし
print(np.max(Y_hat, axis=1)) # axix=1 を指定

8
[4 6 8]


## argmax 関数の利用例

In [29]:
print(np.argmax(Y_hat)) # axis 指定なし
print(np.argmax(Y_hat, axis=1)) # axix=1 を指定

5
[1 0 1]


# 5. 3次元以上の配列

## 行列 A を4つ持つ配列の生成

In [30]:
A_arr = np.array([A, A, A, A])
print(A_arr.shape)

(4, 3, 2)


## A_arr の合計を計算

In [31]:
np.sum(A_arr)

84

## axis = 0 を指定して A_arr の合計を計算

In [32]:
print(np.sum(A_arr, axis=0).shape)
print(np.sum(A_arr, axis=0))

(3, 2)
[[ 4  8]
 [12 16]
 [20 24]]


## axis = (1, 2) を指定して A_arr の合計を計算

In [33]:
print(np.sum(A_arr, axis=(1, 2)))

[21 21 21 21]
